### PR TITLE
Fix deep find method

### LINKED ISSUE #283: Impossible to create New Group
Hello,

I just installed Buttercup for the first time. I wanted to create a new group, but when I click on the button "+ New  Group" i get an "Unhandled Error".

Here is a screenshot:
image

### PR DESCRIPTION
**Pull request by sallar**
Fixes #283

### CODE REVIEW

File: src/shared/utils/collection.js [hunk 1]
```diff
@@ -73,6 +73,10 @@ export function deepAdd(list, id, key, newItem) {
 }
 
 export function deepFindById(list, id, key) {
+  if (!list || !Array.isArray(list)) {
```
Comment (perry-mitchell) [inline src/shared/utils/collection.js]: Wouldn't just `!Array.isArray(list)` work?

Comment (sallar) [inline src/shared/utils/collection.js]: @perry-mitchell you are right sir
